version: '3'
services:
  cms:
    build: ./cms
    env_file:
      - 
    volumes:
      - ./cms:/app
    ports:
      - "8055:8055"
  app:
    build:
      context: ./web
    volumes:
      - ./web:/app
    ports:
      - "3000:3000"