apiVersion: v1
kind: Pod
metadata:
  name: gnh-app
  namespace: gnh
spec:
  containers:
    - name: mypod
      image: gcr.io/tbg-gnh/gnh-app
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 328Mi
      volumeMounts:
        - mountPath: /app/.env
          name: configs
        - mountPath: /app/.env.secrets
          name: secrets
  volumes:
    - name: configs
      configMap:
        name: gnh-app
    - name: secrets
      secret:
        secretName: gnh-app
