steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--cache-from'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - packages/app
      - '-f'
      - packages/app/Dockerfile
    id: Build
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'NEXT_PUBLIC_GA_MEASUREMENT_ID=G-SJX78PVP26'
    secretEnv:
      - STRIPE_ACCOUNT_ID
      - STRIPE_SECRET_KEY
      - ADMIN_TOKEN
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _TRIGGER_ID: ba5256ae-2f50-4176-8ea2-055e8bd2e0e3
  _DEPLOY_REGION: us-central1
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: gnh-app
  _LABELS: gcb-trigger-id=ba5256ae-2f50-4176-8ea2-055e8bd2e0e3

availableSecrets:
  secretManager:
    - versionName: projects/tbg-gnh/secrets/gnh-app-stripe-account/versions/latest
      env: STRIPE_ACCOUNT_ID
    - versionName: projects/tbg-gnh/secrets/gnh-app-stripe-secret/versions/latest
      env: STRIPE_SECRET_KEY
    - versionName: projects/tbg-gnh/secrets/gnh-app-admin-token/versions/latest
      env: ADMIN_TOKEN
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - gnh-app
