apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres-backup
              image: postgres:12
              command: ["/bin/sh"]
              args:
                [
                  "-c",
                  'echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dump -U postgres_admin -h postgres gnh > /backups/backup-$(date +"%m-%d-%Y-%H-%M").sql',
                ]
              env:
                - name: PGPASS
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: PGPASS
                - name: PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: PASSWORD
              volumeMounts:
                - mountPath: /backups
                  name: postgres-storage
          restartPolicy: Never
          volumes:
            - name: postgres-storage
              persistentVolumeClaim:
                claimName: postgres-backup
