namespace: postgres

resources:
  - statefulset-master.yaml
  - statefulset-replica.yaml
  - service.yaml
  - pvc.yaml
  - cronjob.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: postgres
    files:
      - config/postgres.conf
      - config/master.conf
      - config/pg_hba.conf
      - config/create-replica-user.sh

secretGenerator:
  - name: postgres
    env: config/.env
