steps:
 
  # Pull last build for caching
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      ["-c", "docker pull gcr.io/$PROJECT_ID/gnh-admin:latest || exit 0"]
  # Build new image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/gnh-admin",
        "--cache-from",
        "gcr.io/$PROJECT_ID/gnh-admin",
        "--build-arg",
        "${_PATH}",
      ]
  # Push new image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gnh-admin"]
  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "gnh-admin",
        "--image",
        "gcr.io/$PROJECT_ID/gnh-admin",
        "--region",
        "us-central1",
      ]

substitutions:
  _ENV: production
  _PATH: .
  _SERVICE: gnh-admin

images:
  - "gcr.io/$PROJECT_ID/gnh-admin"