apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    client.knative.dev/user-image: gcr.io/tbg-gnh/gnh-admin
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: us-central1
  name: gnh-admin
  namespace: '806946159244'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        client.knative.dev/user-image: gcr.io/tbg-gnh/gnh-admin
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cloudsql-instances: tbg-gnh:us-central1:brotherhood
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
      name: gnh-admin-00004-jas
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: CONFIG_PATH
          value: /directus/config/.env
        image: gcr.io/tbg-gnh/gnh-admin
        ports:
        - containerPort: 8055
          name: http1
        resources:
          limits:
            cpu: 1000m
            memory: 256Mi
        volumeMounts:
        - mountPath: /directus/config
          name: secret-90221671-65eb-4064-b1c6-4fa3bb209e09
          readOnly: true
      serviceAccountName: 806946159244-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
      - name: secret-90221671-65eb-4064-b1c6-4fa3bb209e09
        secret:
          items:
          - key: latest
            path: .env
          secretName: gnh-admin-env
  traffic:
  - latestRevision: true
    percent: 100
